ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 15

#constante inimigos
SPAWN_COOLDOWN = 400

#constante torres
TURRET_LEVELS = 4
BUY_COST = 1
UPGRADE_COST = 75
KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5